Logistic Regression Files, some overfitting changes
machinelearningmindset/machine-learning-course pull request #10
Opened 2019-03-28 21:17 UTC by weric16

Within Logistic Regression, I have a table that I cannot get working.  I want to keep messing around with it, but I'm not sure what is wrong.  I am using the rst basic table, but I think the spacing is off somehow.

2019-03-28 21:19 UTC, weric16 commented
@hokie45

2019-03-28 21:19 UTC, weric16 commented
Here's a link to the tutorial I am using for the table that I can't get to work. http://docutils.sourceforge.net/docs/user/rst/quickref.html#tables

2019-03-29 16:10 UTC, hokie45 commented on docs/source/content/overview/overfitting.rst
> +A model suffers from **Overfitting** when it has learned too much from the training data, and does not perform well in practice as a result.  This is usually caused by the model having too much expos
Could you add a picture for overfitting

2019-03-29 16:28 UTC, hokie45 requested changes

2019-03-29 16:28 UTC, hokie45 commented on docs/source/content/overview/overfitting.rst
> +A model suffers from **Underfitting** when it has not learned enough from the training data, and does not perform well in practice as a result.  As a direct contrast to the previous idea, this issue
Same thing, can you add a picture, and explain why its underfitting

2019-03-29 16:28 UTC, hokie45 commented on docs/source/content/overview/overfitting.rst
> +A model suffers from **Overfitting** when it has learned too much from the training data, and does not perform well in practice as a result.  This is usually caused by the model having too much expos
Could you add a picture of overfitting, and expain why it's overfitting

2019-03-29 16:28 UTC, hokie45 commented on docs/source/content/overview/overfitting.rst
Can you add a picture of what a good fit looks like?

2019-03-29 16:28 UTC, hokie45 commented on docs/source/content/supervised/logistic_regression.rst
> +  Studying      Success
Yeah im not sure why this table isn't working, you might just have to make it a picture or something

2019-03-29 16:28 UTC, hokie45 commented on code/supervised/Logistic_Regression/logistic_ex1.py
> +from sklearn.datasets import load_iris
When i run the code i get this "[0 0]
[[9.81797141e-01 1.82028445e-02 1.44269293e-08]
 [9.71725476e-01 2.82744937e-02 3.01659208e-08]]
0.9733333333333334". 
Then i also get an warning"ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)".
Maybe you can just explain what these numbers mean, and if you also get this error maybe explain what it is

2019-03-29 16:28 UTC, hokie45 commented on code/overview/overfitting/example.py
> +print(__doc__)
I would add some more comments to these explaining what some of the lines do

2019-03-29 18:24 UTC, mergu requested changes

2019-03-29 18:24 UTC, mergu commented on code/overview/overfitting/example.py
> +print(__doc__)
this code is copied directly from 
https://scikit-learn.org/stable/auto_examples/model_selection/plot_underfitting_overfitting.html

2019-04-02 03:23 UTC, astorfi requested changes
Please comment on the codes.

2019-04-05 23:48 UTC, mergu requested changes
As stated on other PRs, we should be using a line length limit. As it stands, every paragraph here is just one long line. Typically the limit is 80-100 chars

2019-04-07 14:58 UTC, astorfi commented
I will merge it for my records.

2019-04-07 14:59 UTC, merged