Knn revision
machinelearningmindset/machine-learning-course pull request #20
Opened 2019-04-19 02:35 UTC by hokie45

The link to knn.py won't work until the PR is merged with master

2019-04-19 02:52 UTC, weric16 commented
It feels obvious, but still might help to discuss in the source what the graph shows for the code.  An idea is to add a comment with the code for showing the boundary that would tell the reader what the boundary is and why it is where it is.

2019-04-19 03:11 UTC, BroccoliHijinx reviewed
See if you can create a visual for brute force, K-D, or both.  I think that would add a lot to the doc, and those sections look a little bare at the moment.

2019-04-19 03:11 UTC, BroccoliHijinx commented on docs/source/content/supervised/knn.rst
> +look at is the brute force method and the K-D tree method.
should be the two ways *are*...

2019-04-19 03:11 UTC, BroccoliHijinx commented on docs/source/content/supervised/knn.rst
> +to use this method when the dimensions are small or the number of points are small.
Why is that? Say something about how long that would take, and why.  It will also lead into the next section well.

2019-04-19 03:11 UTC, weric16 commented on docs/source/content/supervised/knn.rst
> +So why would someone use this classifier over another? Is this the best classifier? The answer to these questions is that it depends.
the answer to both of these questions are that it depends.

2019-04-19 03:11 UTC, weric16 commented on docs/source/content/supervised/knn.rst
> +choose a k that is relatively small. You can also change the algorithm used the options are
...used, the options are...

2019-04-19 03:11 UTC, weric16 commented on docs/source/content/supervised/knn.rst
> +change the time it takes to predict the data. You can change it here in the code, try change the value of n_neighbors to 1.
...try changing the value...

2019-04-22 04:38 UTC, astorfi commented
@hokie45 @weric16 Any activity here?

2019-04-22 18:12 UTC, BroccoliHijinx requested changes
There's a few mechanical things in there, but mainly splitting the discussion of algorithm and k in the code section.  Big picture it looks good though.

2019-04-22 18:12 UTC, weric16 commented on docs/source/content/supervised/knn.rst
> +So, we are trying to identify what class an object is in. To do this we
Identify that you already have a labeled data set, and you're trying to classify other points into one of the categories.  Without the background knowledge, one might be confused as to how you would know any categories at all.

2019-04-22 18:12 UTC, weric16 commented on docs/source/content/supervised/knn.rst
> +How a K-D tree works is that a node in the tree represents and holds data from a n-dimensional
...from *an* n-dimensional graph...

2019-04-22 18:12 UTC, weric16 commented on docs/source/content/supervised/knn.rst
> +when it's time to classify a point we would just look at the where the point will fall in the
...just look at where the point... (an extra the)

2019-04-22 18:12 UTC, weric16 commented on docs/source/content/supervised/knn.rst
> +This is the simplest method. Basically, it's just calculating the Euclidean
define Euclidean distance (simply), for those that might not know the term but are probably aware of the concept

2019-04-22 18:12 UTC, weric16 commented on docs/source/content/supervised/knn.rst
> +- The Brute Method is best when the dimensions of the points or the number of points are small
The brute *force* method

2019-04-22 18:12 UTC, weric16 commented on docs/source/content/supervised/knn.rst
> +not another. It's good to know about other classifiers like Support Vector Machines, and then decide which one best classifies the
Add a link to SVM's docs here

2019-04-22 18:12 UTC, weric16 commented on docs/source/content/supervised/knn.rst
> +Just make sure you have, data points and an array of targets to classify those data points.
remove the comma here

2019-04-22 18:12 UTC, weric16 commented on docs/source/content/supervised/knn.rst
> +{‘auto’, ‘ball_tree’, ‘kd_tree’, ‘brute’}. These don't change the output of the prediction they just will
...prediction*,* they *will just*...

2019-04-22 18:12 UTC, weric16 commented on docs/source/content/supervised/knn.rst
> +change the time it takes to predict the data. You can change it here in the code, try changing the value of n_neighbors to 1.
changing n_neighbors is not what is being discussed in this paragraph, I suggest making a new paragraph to explicitly discuss changing the neighbors.

2019-04-22 18:12 UTC, weric16 commented on docs/source/content/supervised/knn.rst
> +change the time it takes to predict the data. You can change it here in the code, try changing the value of n_neighbors to 1.
Actually, it goes back and forth.  Definitely separate the algorithm and the k into two separate paragraphs.

2019-04-22 18:12 UTC, weric16 commented on docs/source/content/supervised/knn.rst
> +will want a higher k value otherwise choose a smaller k like 1, 3 or 5. You can experiment by choosing a very high k greater than 100.
...value*,* otherwise...

2019-04-23 16:19 UTC, astorfi commented
@hokie45 @weric16 Please confirm when it is completed.

2019-04-23 21:26 UTC, BroccoliHijinx requested changes
One small change.  Fix that line and the changes are approved.

2019-04-23 21:26 UTC, weric16 commented on docs/source/content/supervised/knn.rst
> +How an K-D tree works is that a node in the tree represents and holds data from a n-dimensional
This was the wrong a to switch, I meant the one at the end of the sentence.  The line should read: How a K-D tree works is that a node in the tree represents and holds data from an n-dimensional

2019-04-24 13:05 UTC, hokie45 commented
@astorfi @weric16 This PR should be completed now.

2019-04-25 15:26 UTC, BroccoliHijinx approved these changes
Approved.

2019-04-26 19:51 UTC, merged