This is my txt file for the k-nearest neighbors
machinelearningmindset/machine-learning-course pull request #5
Opened 2019-03-01 20:54 UTC by hokie45

2019-03-01 20:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/machinelearningmindset/machine-learning-for-everybody?pullRequest=5) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/machinelearningmindset/machine-learning-for-everybody?pullRequest=5) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/machinelearningmindset/machine-learning-for-everybody?pullRequest=5) it.</sub>

2019-03-06 01:43 UTC, astorfi commented
@hokie45 Please sign the CLA first. Thanks

2019-03-13 22:01 UTC, astorfi requested changes
Please change the format to .md or .rst

2019-03-18 19:04 UTC, hokie45 commented
I changed it to rst format

2019-03-21 15:02 UTC, merged

2019-03-21 15:03 UTC, astorfi commented
Thank you